version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      DB_ROOT_PASSWORD: rootpass
      DB_DATABASE: tienda
      DB_USER: tiendauser
      DB_PASSWORD: tiendapass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    build: .
    depends_on:
      - db
    env_file:
      - .env.dev
    #environment:
    #  DB_HOST: db
    #  DB_PORT: 3306
    #  DB_NAME: tienda
    #  DB_USER: tiendauser
    #  DB_PASSWORD: tiendapass
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  mysql_data:
